microtype/models.py
import datetime
from microtype import db
from hashlib import md5
from mongoengine.queryset import queryset_manager
class User(db.Document):
    email = db.EmailField(required=True)
    nickname = db.StringField(max_length=20,required=True)
    password = db.StringField(max_length=48,required=True)
    about_me = db.StringField(max_length=255)

    def __repr__(self):
        return '<User %r>' % (self.email)

class Post(db.Document):
    created_at = db.DateTimeField(default = datetime.datetime.now)
    title = db.StringField(max_length=255, required=True)
    content = db.StringField(required=True)
    tag = db.StringField(required=True)
    author = db.ReferenceField(User)

    @queryset_manager
    def objects(cls, queryset):
        return queryset.order_by('-created_at')

    def __unicode__(self):
        return self.title

    def __repr__(self):
        return '<Post %r>' % (self.title)

class Links(db.Document):
    url = db.StringField(max_length=255, required=True)
    text = db.StringField(max_length=255)

    def __unicode__(self):
        return self.url

    def __repr__(self):
        return '<Links %r>' % (self.url)

microtype/__init__.py
from flask import Flask
from flask.ext.mongoengine import MongoEngine
from . import config


app = Flask(__name__)
app.config.from_object(config)
db = MongoEngine(app)
from helper_functions import generate_csrf_token
from microtype.models import Post
from microtype.models import User
from .main import main as main_blueprint
from .auth import auth as auth_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(auth_blueprint, url_prefix="/auth")
app.jinja_env.globals['csrf_token'] = generate_csrf_token
app.jinja_env.globals['tags'] = Post._get_collection().aggregate([{'$group':{'_id':'$tag','count':{'$sum':1}}},{'$sort':{'count': -1}},{'$limit': 10}])['result']
app.jinja_env.globals['recent_posts'] = Post.objects[:5]
app.jinja_env.globals['about_me'] = User.objects.get(email="shadowxqq@gmail.com")

microtype/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)
from . import views

microtype/main/views.py
#-*- coding:utf-8 -*-
import datetime
from flask import render_template,request,g,flash,redirect,url_for,session,Response
from werkzeug.contrib.atom import AtomFeed
from microtype.main import main
from microtype.models import Post,User
from microtype.helper_functions import login_required,gen_user_passwrod
from microtype.config import BLOG_TITLE

@main.route("/")
@main.route("/index/<int:page>")
def index(page=1):
    pagination = Post.objects.paginate(page=page, per_page=3)
    posts = pagination.items
    return render_template('index.html', title = "Index | "+ BLOG_TITLE, posts = posts, pagination = pagination)

@main.route("/post/<title>")
def posts(title=None):
    post = Post.objects.get_or_404(title=title)
    return render_template('post.html',title = post.title+" | "+BLOG_TITLE, post = post)

@main.route("/links")
def links():
    return render_template("links.html", title = "Links | "+ BLOG_TITLE)

@main.route("/user/<username>")
@login_required()
def user(username = None):
    user = User.objects.get_or_404(nickname = username)
    return render_template("profile.html", profile=user, title= "Profile | "+BLOG_TITLE, username=session.get("nickname"))

@main.route("/editprofile/<username>", methods=["get","post"])
@login_required()
def editprofile(username = None):
    user = User.objects.get_or_404(nickname = username)
    if request.method == "POST":
        about_me = request.form.get("about_me")
        pass1 = request.form.get("password1")
        pass2 = request.form.get("password2")
        nickname = request.form.get("nickname")
        if about_me and nickname:
            user.about_me = about_me
            user.nickname = nickname
            session["nickname"] = nickname
            if pass1 == None and pass2 == None:
                user.save()
            elif pass1 == pass2 and pass1 and pass2 != None:
                user.password = gen_user_passwrod(pass1)
                print user.password
                user.save()
            else:
                user.save()
            flash(u"修改成功", "success")
        else:
            flash(u"错误", "error")

    return render_template("editprofile.html", profile=user, title="Edit | "+BLOG_TITLE, username=session.get("nickname"))

@main.route("/admin")
@login_required()
def admin():
    return render_template("admin.html", title = "Admin | "+ BLOG_TITLE)

@main.route("/admin/newpost", methods=["post","get"])
@login_required()
def newpost():
    if request.method == "POST":
        posttitle = request.form.get("title")
        posttag = request.form.get("tag")
        posthtml = request.form.get("content")
        author = User.objects(email=g.user).first()
        if request.form.get("post-id"):
            post = Post.objects(id=request.form.get("post-id")).first()
            post.title = posttitle
            post.tag = posttag
            post.content = posthtml
            post.author = author
            post.created_at = datetime.datetime.now
            post.save()
            flash("Update success..","success")
        else:
            post = Post(title=posttitle, content = posthtml, tag=posttag, author = author)
            post.save()
            flash("Add success..","success")

    return render_template("newpost.html", title = "New Post | "+BLOG_TITLE)

@main.route("/admin/postlist/<int:page>")
@login_required()
def postlist(page=1):
    pagination = Post.objects.paginate(page=page, per_page=5)
    session['page'] = request.path.split('/')[3]
    posts = pagination.items
    return render_template("postlist.html", title = "Posts | "+ BLOG_TITLE, posts = posts, pagination = pagination)

@main.route("/admin/editpost/<id>")
@login_required()
def editpost(id=None):
    post = Post.objects(id=id).first()
    return render_template("editpost.html", title="Editpost | "+BLOG_TITLE, post=post)

@main.route("/admin/removepost/<id>")
@login_required()
def removepost(id=None):
    if Post.objects().count() > 1:
        post = Post.objects(id=id)
        post.delete()
        print session.get("page")
        flash("Remove success..",'success')
        return redirect(url_for("main.postlist", page=session.get("page")))
    else:
        flash("Need to be at least one post..", 'error')

@main.route("/admin/settings")
@login_required()
def settings():
    pass

@main.route("/tags/<tag>")
def tags(tag = None):
    posts = Post.objects(tag=tag)
    tags = Post._get_collection().aggregate([
        {'$group':{'_id':'$tag','count':{'$sum':1}}},
        {'$sort':{'count': -1}},
        {'$limit': 10}
    ])
    tags = tags["result"]
    return render_template("tags.html", title = "Tags | "+ BLOG_TITLE, posts = posts, tags = tags)

@main.route("/feed")
def feed():
    _feed = AtomFeed(title = BLOG_TITLE,
                     icon = r"http://www.rdoge.cc/static/favicon.ico",
                     url=request.url_root
                     )

    posts = Post.objects[:12]

    for _post in posts:
        _feed.add(
            title = _post.title,
            content = _post.content,
            content_tyep = "html",
            author = _post.author.nickname,
            url = url_for("main.posts", title=_post.title, _external=True),
            published = _post.created_at,
            updated = _post.created_at
        )

    return Response(_feed.to_string(), mimetype="application/xml")

@main.app_errorhandler(404)
def page_not_found(error):
   return render_template("404.html", title = "Not found | "+BLOG_TITLE)


@main.app_template_filter('formatdate')
def format_datetime_filter(input_value, format_="%Y/%m/%d"):
    return input_value.strftime(format_)

microtype/templates/_macros.html
            {%- macro pagination_page(pagination, endpoint) %}
            <div class="am-pagination blog-pagination">
                <li{% if not pagination.has_prev %} class="am-pagination-prev am-disabled"{% endif %}>
                    <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">上一页</a>
                </li>
                <li{% if not pagination.has_next %} class="am-pagination-next am-disabled"{% else %} class="am-pagination-next"{% endif %}>
                    <a href="{% if pagination.has_next %}{{ url_for(endpoint, page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">下一页</a>
                </li>
            </div>
            {%- endmacro %}

microtype/templates/admin.html
<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ title }}}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" type="image/png" href="{{ url_for('static', filename = 'favicon.ico') }}">
  <link rel="apple-touch-icon-precomposed" href="{{ url_for('static', filename = 'favicon.ico') }}">
  <link rel="stylesheet" href="//cdn.amazeui.org/amazeui/2.2.1/css/amazeui.min.css"/>
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/admin.css') }}">
</head>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->
<header class="am-topbar admin-header">
  <div class="am-topbar-brand">
    <strong>Pytype</strong> <small>后台管理</small>
  </div>

  <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="topbar-collapse">

    <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
      <li class="am-dropdown" data-am-dropdown>
        <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
          <span class="am-icon-user"></span> Me <span class="am-icon-caret-down"></span>
        </a>
        <ul class="am-dropdown-content">
          <li><a href="#""><span class="am-icon-user"></span> Profile</a></li>
          <li><a href="#"><span class="am-icon-cog"></span> 设置</a></li>
          <li><a href="{{ url_for("auth.logout") }}"><span class="am-icon-power-off"></span> Logout</a></li>
        </ul>
      </li>
    </ul>
  </div>
</header>

<div class="am-cf admin-main">
  <!-- sidebar start -->
  <div class="admin-sidebar am-offcanvas" id="admin-offcanvas">
    <div class="am-offcanvas-bar admin-offcanvas-bar">
      <ul class="am-list admin-sidebar-list">
        <li><a href="{{ url_for("main.admin") }}"><span class="am-icon-home"></span> 首页</a></li>
        <li><a href="{{ url_for("main.newpost" )}}"><span class="am-icon-book"></span> New Post</a></li>
        <li><a href="admin-form.html"><span class="am-icon-pencil-square-o"></span> 表单</a></li>
        <li><a href="#"><span class="am-icon-sign-out"></span> 注销</a></li>
      </ul>

      <div class="am-panel am-panel-default admin-sidebar-panel">
        <div class="am-panel-bd">
          <p><span class="am-icon-tag"></span> 公告</p>
          <p>时光静好，与君语；细水流年，与君同。—— Amaze UI</p>
        </div>
      </div>
    </div>
  </div>
  <!-- sidebar end -->

  <!-- content start -->
  <div class="admin-content">

    <div class="am-cf am-padding">
      <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">首页</strong> / <small>Welcome</small></div>
    </div>
    <div class="am-g">
      <div class="am-u-sm-12">
          <h1>欢迎回来!</h1>
      </div>
    </div>
  <!-- content end -->

</div>

<a class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="{{ url_for("static",filename="assets/js/polyfill/rem.min.js") }}"></script>
<script src="{{ url_for("static",filename="assets/js/polyfill/respond.min.js") }}"></script>
<script src="{{ url_for("static",filename="assets/js/amazeui.legacy.js") }}"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script src="//cdn.amazeui.org/amazeui/2.2.1/js/amazeui.min.js"></script>
<!--<![endif]-->
<script src="{{ url_for("static",filename="assets/js/app.js") }}"></script>
</body>
</html>

microtype/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
{%- block head %}
    <meta charset="utf-8">
    {% block title %}<title>{{ title }}</title>{% endblock title %}
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="//cdn.amazeui.org/amazeui/2.2.1/css/amazeui.min.css" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/base.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/github.css') }}" type="text/css">
    {%- block css %}

    {%- endblock css %}
{%- endblock head %}
</head>
<body>
    {%- block navbar %}
    <header class="am-topbar">
        <h2 class="am-topbar-brand">
            <a href="{{ url_for("main.index") }}">Home</a>
        </h2>
        <div class="am-collapse am-topbar-collapse" id="doc-topbar-collapse">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <!--<li{% if request.path == "/" %} class="am-active"{% elif "index" in request.path %} class="am-active"{% endif %}><a href="{{ url_for("main.index")}}">Index</a></li>-->
                {%- if g.user %}
                <li><a href="{{ url_for("auth.logout") }}">Logout</a></li>
                {%- else %}
                <li><a href="{{ url_for("auth.login") }}">Login</a></li>
                {%- endif %}
                <li{% if "links" in request.path %} class="am-active"{% endif %}><a href="{{ url_for("main.links") }}">Friends</a></li>
                <li><a href="{{ url_for("main.feed")}}"><span class="am-icon-rss"></span> RSS</a> </li>
                {%- if g.user %}
                <li class="am-dropdown" data-am-dropdown="">
                    <a class="am-dropdown-toggle" data-am-dropdown-toggle="" href="javascript:;">Menu <span class="am-icon-caret-down"></span></a>
                    <ul class="am-dropdown-content">
                        <li><a href="{{ url_for("main.user", username = g.nickname) }}"><span class="am-icon-user"></span> 资料</a></li>
                        <li><a href="#"><span class="am-icon-cog"></span> 设置</a></li>
                        <li><a href="{{ url_for("main.newpost" )}}"><span class="am-icon-edit"></span> 发布文章</a></li>
                        <li><a href="{{ url_for("main.postlist", page=1) }}"><span class="am-icon-list-alt"></span> 所有文章</a></li>
                        <li><a href="{{ url_for("auth.logout") }}"><span class="am-icon-power-off"></span> 退出</a></li>
                    </ul>
                </li>
                {%- endif %}
            </ul>
            <form class="am-topbar-form am-topbar-right am-form-inline am-topbar-left" role="search" action="#">
                <div class="am-form-group">
                    <input type="text" class="am-form-field am-input-sm" placeholder="_(:з」∠)_">
                </div>
                <button type="submit" class="am-btn am-btn-default am-btn-sm">Search</button>
            </form>
        </div>
    </header>
    {%- endblock navbar %}
    {%- block body %}
    <div class="am-g am-g-fixed blog-g-fixed">
        {%- with messages = get_flashed_messages(with_categories=True) %}
        {%- if messages %}
            {%- for category, message in messages %}
                {%- if category =="success" %}
        <div class="am-alert am-alert-success" data-am-alert><button type="button" class="am-close">&times;</button>{{ message }}</div>
                {%- else %}
        <div class="am-alert am-alert-warning" data-am-alert><button type="button" class="am-close">&times;</button>{{ message }}</div>
                {%- endif %}
            {%- endfor %}
        {%- endif %}
        {%- endwith %}
        {%- block page_content %}
        {%- endblock page_content %}
    </div>
    {%- endblock body %}
    <footer class="blog-footer">
        <small>&copy; Copyright Nightraid. powered by <a href="#">Flask</a></small>
    </footer>
    {% block javascript %}
<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="//cdn.amazeui.org/amazeui/2.2.1/js/amazeui.legacy.min.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script src="//cdn.amazeui.org/amazeui/2.2.1/js/amazeui.min.js"></script>
<script src="{{ url_for('static', filename='js/highlight.pack.js') }}"></script>
<script>hljs.initHighlightingOnLoad();</script>
<!--<![endif]-->
    {%- endblock %}
</body>
</html>

microtype/templates/editpost.html
{%- extends "base.html" %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="markitup/skins/simple/style.css") }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="markitup/sets/html/style.css") }}" />
{%- endblock css %}
{% block page_content -%}
    <div class="am-u-md-9">
        <div class="page-header">
            <h1>编辑文章</h1>
        </div>
        <form class="am-form" action="{{ url_for("main.newpost") }}" method="post" id="commentform">
        <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
        <input name="post-id" type="hidden" value="{{ post.id }}">
        <div class="am-form-group">
            <label for="title">标题:</label> <input type="text" name="title" id="title" value="{{ post.title }}" required />
            <label for="tag">标签:</label> <input type="text" name="tag" id="tag" value="{{ post.tag }}" required />
            <label for="html">编辑框:</label><textarea id="html" name="content" cols="40" rows="10">{{ post.content }}</textarea>
            <button type="submit" class="am-btn am-btn-primary">提交</button>
        </div>
        </form>
    </div>
{%- endblock page_content %}
{% block javascript %}
{{ super() }}
<script type="text/javascript" src="{{ url_for("static", filename="markitup/jquery.markitup.js") }}"></script>
<script type="text/javascript" src="{{ url_for("static", filename="markitup/sets/html/set.js") }}"></script>
<script language="javascript">
$(document).ready(function()	{
   $('#html').markItUp(mySettings);
});
</script>
{% endblock javascript %}

microtype/templates/editprofile.html
{%- extends "base.html" %}
        {% block page_content %}
        <div class="am-u-md-9">
            <h1>资料</h1><hr />
            <div class="edit_profile">
                <form class="am-form" method="post" action="{{ url_for("main.editprofile", username=username) }}">
                <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
                <div class="am-form-group">
                    <label for="nickname">昵称:</label>
                    <input type="text" name="nickname" id="nickname" value="{{ profile.nickname }}" required /><br />
                    <label for="about_me">介绍:</label>
                    <input type="text" name="about_me" id="about_me" value="{{ profile.about_me }}" required /><br />
                    <label for="password1">密码:</label>
                    <input type="password" name="password1" id="password1" placeholder="password"  /><br />
                    <label for="password2">确认密码:</label>
                    <input type="password" name="password2" id="password2" placeholder="password"  /><br />
                    <br />
                    <button type="submit" class="am-btn am-btn-primary">更新</button>
                </div>
                </form>
            </div>
        </div>
        {%- endblock page_content %}

microtype/templates/index.html
{%- extends "base.html" %}
{%- import "_macros.html" as macros %}
        {% block page_content -%}
        <div class="am-u-md-9">
            {%- for post in posts %}
            <article class="blog-main">
                <h3 class="am-article-title blog-title">
                    <a href="{{ url_for('main.posts', title = post.title ) }}">{{ post.title | safe }}</a>
                </h3>
                <h4 class="am-article-meta blog-meta">
                    <span class="am-icon-clock-o"></span>
                    作者: {{ post.author.nickname }} 日期: {{ post.created_at | formatdate }} 标签: <a href="{{ url_for('main.tags', tag = post.tag) }}">{{ post.tag }}</a>
                </h4>
                <div class="am-g blog-content">
                    <div class="am-u-lg-12">
                         {{ post.content | safe }}
                    </div>
                </div>
            </article>
            <hr class="am-article-divider blog-hr">
            {%- endfor %}
            {{ macros.pagination_page(pagination, "main.index") }}
        </div>
{% include "sidebar.html" %}
        {%- endblock page_content %}

microtype/templates/links.html
{%- extends "base.html" %}
{% block page_content %}
    <div class="am-u-md-9">
        <div class="page-header">
            <h1>菊苣们</h1>
        </div>
        <div class="links">
            <p><a href="http://www.baidu.com">百度</a></p>
        </div>
    </div>
{%- endblock page_content %}

microtype/templates/newpost.html
{%- extends "base.html" %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="markitup/skins/simple/style.css") }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="markitup/sets/html/style.css") }}" />
{%- endblock css %}
{% block page_content -%}
    <div class="am-u-md-9">
        <div class="page-header">
            <h1>发布文章</h1>
        </div>
        <form class="am-form" action="{{ url_for("main.newpost") }}" method="post" id="commentform">
        <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
        <div class="am-form-group">
            <label for="title">标题:</label> <input type="text" name="title" id="title" value="" required />
            <label for="tag">标签:</label> <input type="text" name="tag" id="tag" value="" required />
            <label for="html">编辑框:</label><textarea id="html" name="content" cols="40" rows="10"></textarea>
            <button type="submit" class="am-btn am-btn-primary">提交</button>
        </div>
        </form>
    </div>
{%- endblock page_content %}
{% block javascript %}
{{ super() }}
<script type="text/javascript" src="{{ url_for("static", filename="markitup/jquery.markitup.js") }}"></script>
<script type="text/javascript" src="{{ url_for("static", filename="markitup/sets/html/set.js") }}"></script>
<script language="javascript">
$(document).ready(function()	{
   $('#html').markItUp(mySettings);
});
</script>
{% endblock javascript %}

microtype/templates/post.html
{% extends "base.html"%}
        {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/post.css') }}" type="text/css">
        {%- endblock css %}
        {% block page_content %}
            <div class="am-u-md-9">
                <article class="blog-main">
                    <h1 class="am-article-title title">{{ post.title }}</h1>
                    <h4 class="am-article-meta blog-meta">
                    <p>
                        <span class="am-icon-clock-o"></span>
                        作者: {{ post.author.nickname }} 日期: {{ post.created_at | formatdate }} 标签: <a href="{{ url_for('main.tags', tag = post.tag) }}">{{ post.tag }}</a>
                    </p>
                    </h4>
                    <hr>
                      {{ post.content | safe }}
                </article>
                <!-- 多说评论框 start -->
	            <div class="ds-thread" data-thread-key="{{ post.title }}" data-title="{{ post.title }}" data-url="{{ url_for('main.posts' , title = post.title)}}"></div>
                <!-- 多说评论框 end -->
                <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
                <script type="text/javascript">
                var duoshuoQuery = {short_name:"maodan"};
	                (function() {
		                var ds = document.createElement('script');
		                ds.type = 'text/javascript';ds.async = true;
		                ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		                ds.charset = 'UTF-8';
		                (document.getElementsByTagName('head')[0]
		                || document.getElementsByTagName('body')[0]).appendChild(ds);
	                })();
	            </script>
                <!-- 多说公共JS代码 end -->
            </div>
{% include "sidebar.html" %}
        {%- endblock page_content %}

microtype/templates/postlist.html
{%- extends "base.html" %}
{%- import "_macros.html" as macros %}
{% block page_content %}
    <div class="am-u-md-9">
        <div class="page-header">
            <h1>全部文章</h1>
        </div>
        <div class="lists">
            <a href="{{ url_for("main.newpost") }}" class="am-btn am-btn-primary">发布文章</a>
            <table class="am-table am-table-striped am-table-hover table-main">
                <thead>
                <tr>
                    <th class="table-title">标题</th><th class="table-date am-hide-sm-only">修改日期</th><th class="table-set">操作</th>
                </tr>
                </thead>
                <tbody>
                {%- for post in posts %}
                <tr>
                    <td><a href="{{ url_for("main.posts", title=post.title) }}">{{ post.title }}</a></td>
                    <td class="am-hide-sm-only">{{ post.created_at | formatdate }}</td>
                    <td class="am-hide-sm-only"><a class="am-icon-edit" href="{{ url_for("main.editpost", id=post.id) }}"></a>&nbsp;&nbsp;<a  href="{{ url_for("main.removepost", id=post.id) }}" class="am-icon-remove"></a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {{ macros.pagination_page(pagination, "main.postlist") }}
    </div>
{%- endblock page_content %}

microtype/templates/profile.html
{%- extends "base.html" %}
        {% block page_content %}
        <div class="am-u-md-9">
            <h1>资料</h1><hr />
            <div class="profile">
                <h2><p>{{ profile.nickname }}</p></h2>
                <p>{{ profile.about_me }}</p>
                <a href="{{ url_for("main.editprofile", username=username) }}" class="am-btn am-btn-primary">编辑资料</a>
            </div>
        </div>
        {%- endblock page_content %}

microtype/templates/sidebar.html
        <div class="am-u-md-3 blog-sidebar">

            <div class="am-panel-group">
                <section class="am-panel am-panel-default">
                    <div class="am-panel-hd">关于我</div>
                    <div class="am-panel-bd">
                        <p>{{ about_me.about_me }}</p>
                    </div>
                </section>
            </div>

            <div class="am-panel-group">
                <section class="am-panel am-panel-default">
                    <div class="am-panel-hd">最近文章</div>
                    <div class="am-list">
                        {%- for recent_post in recent_posts%}
                        <li><a href="{{ url_for("main.posts", title=recent_post.title )}}">{{ recent_post.title }}</a></li>
                        {%- endfor %}
                    </div>
                </section>
            </div>
             <div class="am-panel-group">
                <section class="am-panel am-panel-default">
                    <div class="am-panel-hd">标签</div>
                    <div class="am-list blog-list">
                        {%- for tag in tags %}
                        <li><a href="{{ url_for('main.tags', tag=tag._id) }}">{{ tag._id }} <sup><span class="am-badge am-badge-success am-round">{{ tag.count }}</span></sup></a></li>
                        {%- endfor %}
                    </div>
                </section>
            </div>

        </div>

microtype/templates/tags.html
{%- extends "base.html" %}
{%- import "_macros.html" as macros %}
        {% block page_content -%}
        <div class="am-u-md-9">
            {%- for post in posts %}
            <article class="blog-main">
                <h3 class="am-article-title blog-title">
                    <a href="{{ url_for('main.posts', title = post.title ) }}">{{ post.title }}</a>
                </h3>
                <h4 class="am-article-meta blog-meta">
                    <span class="am-icon-clock-o"></span>
                    作者: {{ post.author.nickname }} 日期: {{ post.created_at | formatdate }} 标签: <a href="#">{{ post.tag }}</a>
                </h4>
                <div class="am-g blog-content">
                    <div class="am-u-lg-12">
                         {{ post.content | safe }}
                    </div>
                </div>
            </article>
            <hr class="am-article-divider blog-hr">
            {%- endfor %}
        </div>
{% include "sidebar.html" %}
        {%- endblock page_content %}